<?xml version="1.0"?>

<config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../../../../lib/internal/Magento/Framework/ObjectManager/etc/config.xsd">
	<!--
		2016-03-18
		Bug: the @see \Magento\Sales\Model\Order\CreditmemoRepository::save() method
		misses (does not log and does not show) the actual exception message
		on a credit memo saving falure.
		https://mage2.pro/t/973
	-->
	<type name="Magento\Sales\Model\Order\CreditmemoRepository">
		<plugin
			name="Prisma\TodoPago\Model\Order\CreditmemoRepository"
			type="Prisma\TodoPago\Model\Order\CreditmemoRepository"
		/>
	</type>

	<type name="Prisma\TodoPago\Model\Factory\Connector" shared="false">
        <arguments>
            <argument name="scopeConfig" xsi:type="object">\Magento\Framework\App\Config\ScopeConfigInterface</argument>
        </arguments>
    </type>
</config>
